= Open Application Standard Platform for Java (OASP4J)

Welcome to the Java edition of OASP. OASP4J is documented by a platform guide (see the side-bar of this wiki) to be used in your projects.

You will find the latest stable versions of documents generated from this wiki here:

* http://oasp.github.io/oasp4j/2.0.0/OASP4J.pdf[stable OASP platform guide as PDF].
If you want to search the wiki you might want to try https://github.com/linyows/github-wiki-search[github-wiki-search].

== For contributors
Contributors who like to contribute to the platform OASP, please find menu-section OASP Development on the right. Please read link:oasp-ide-setup[IDE setup] and link:oasp-code-contributions[Contribute code to OASP] to get started. If you want to contribute to the OASP-documentation (this wiki) please read the very important notes on link:oasp-documentation[Maintain OASP documentation] first.

Contributions and improvements to OASP are very welcome. However, you should be aware of the following aspects:

* Your contributions will become part of OASP4J documentation and get licensed under creative commons (see footer).
